create table public.categorias (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre text not null,
  constraint categorias_pkey primary key (id)
) TABLESPACE pg_default;

create table public.productos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre text null,
  precio double precision null,
  peso double precision null,
  id_cat bigint null,
  constraint productos_pkey primary key (id),
  constraint productos_id_cat_fkey foreign KEY (id_cat) references categorias (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.inventario (
  id_prod bigint not null,
  created_at timestamp with time zone not null default now(),
  cantidad bigint null default 0,
  constraint inventario_pkey primary key (id_prod),
  constraint inventario_id_prod_fkey foreign KEY (id_prod) references productos (id) on delete CASCADE,
  constraint inventario_cantidad_check check ((cantidad >= 0))
) TABLESPACE pg_default;