create table
  public.categorias (
    id bigint generated by default as identity not null,
    created_at timestamp
    with
      time zone not null default now (),
      nombre text not null,
      constraint categorias_pkey primary key (id)
  ) TABLESPACE pg_default;

create table
  public.productos (
    id bigint generated by default as identity not null,
    created_at timestamp
    with
      time zone not null default now (),
      nombre text null,
      precio double precision null,
      peso double precision null,
      id_cat bigint null,
      constraint productos_pkey primary key (id),
      constraint productos_id_cat_fkey foreign KEY (id_cat) references categorias (id) on update CASCADE on delete set null
  ) TABLESPACE pg_default;

create table
  public.inventario (
    id_prod bigint not null,
    created_at timestamp
    with
      time zone not null default now (),
      cantidad bigint null default 0,
      constraint inventario_pkey primary key (id_prod),
      constraint inventario_id_prod_fkey foreign KEY (id_prod) references productos (id) on delete CASCADE,
      constraint inventario_cantidad_check check ((cantidad >= 0))
  ) TABLESPACE pg_default;

-- Create an ENUM for roles to avoid typos
create type user_role as enum ('cliente', 'administrador');

create table
  public.perfiles (
    id uuid references auth.users on delete cascade not null primary key,
    nombre text not null,
    apellido text not null,
    correo text unique not null, -- Syncs with auth.users email
    rol user_role default 'cliente',
    direccion text,
    telefono text,
    created_at timestamp
    with
      time zone default now ()
  );

create table
  public.carrito (
    id bigint generated by default as identity primary key,
    usuario_id uuid references public.perfiles (id) on delete cascade not null,
    producto_id bigint references public.productos (id) on delete cascade not null,
    cantidad int not null default 1 check (cantidad > 0),
    created_at timestamp
    with
      time zone default now (),
      -- Prevents duplicate rows for the same product in a user's cart
      constraint unique_usuario_producto unique (usuario_id, producto_id)
  );

-- Header of the order
create table
  public.pedidos (
    id bigint generated by default as identity primary key,
    usuario_id uuid references public.perfiles (id) on delete set null,
    total double precision not null default 0,
    estado text default 'pendiente', -- e.g., 'pendiente', 'pagado', 'cancelado'
    fecha_pedido timestamp
    with
      time zone default now ()
  );

-- Lines of the order (Historical data)
create table
  public.pedido_detalles (
    id bigint generated by default as identity primary key,
    pedido_id bigint references public.pedidos (id) on delete cascade,
    producto_id bigint references public.productos (id) on delete set null,
    cantidad int not null,
    precio_unitario_historico double precision not null -- Price at the time of purchase
  );

INSERT INTO
  auth.users (
    id,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_user_meta_data
  )
VALUES
  (
    'a1111111-1111-1111-1111-111111111111',
    'david@minimarket.com',
    crypt ('password123', gen_salt ('bf')),
    now (),
    '{"nombre": "David", "apellido": "Calderon"}'
  ),
  (
    'b2222222-2222-2222-2222-222222222222',
    'saul@minimarket.com',
    crypt ('password123', gen_salt ('bf')),
    now (),
    '{"nombre": "Saul", "apellido": "Gonzales"}'
  ),
  (
    'c3333333-3333-3333-3333-333333333333',
    'cliente.test@email.com',
    crypt ('password123', gen_salt ('bf')),
    now (),
    '{"nombre": "Maria", "apellido": "Lopez"}'
  ),
  (
    'd4444444-4444-4444-4444-444444444444',
    'roberto.g@email.com',
    crypt ('robertoPass2024', gen_salt ('bf')),
    now (),
    '{"nombre": "Roberto", "apellido": "Guzman"}'
  ),
  (
    'e5555555-5555-5555-5555-555555555555',
    'elena.m@email.com',
    crypt ('secureElena!99', gen_salt ('bf')),
    now (),
    '{"nombre": "Elena", "apellido": "Morales"}'
  );